@notesURL = http://localhost:3030

GET {{notesURL}}/

###

GET {{notesURL}}/notes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzI4NGU3NjUyNjI4MzU0OTNmNGUzYWIiLCJlbWFpbCI6Imhhbm5hQGdtYWlsLmZpIiwiaWF0IjoxNjYzNTg5MTk3fQ.H4eXLE-RDFoRYywChs8_Wgk77i6nT4gm4vJs_J8beu0


###

GET {{notesURL}}/notes/1

###

POST {{notesURL}}/notes/
Content-Type: application/json

{
    "text": "Duscha"
}

###

