@baseURL = http://localhost:3030

GET {{baseURL}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzI4NGU3NjUyNjI4MzU0OTNmNGUzYWIiLCJlbWFpbCI6Imhhbm5hQGdtYWlsLmZpIiwiaWF0IjoxNjYzNTg5MTk3fQ.H4eXLE-RDFoRYywChs8_Wgk77i6nT4gm4vJs_J8beu0


### Skapa ny användare, skriv i json format

POST {{baseURL}}/users
Content-Type: application/json 

{
    "email": "hanna@gmail.fi",
    "password": "Password1123"
}

### Logga in

POST {{baseURL}}/users/login
Content-Type: application/json 

{
    "email": "hanna@gmail.fi",
    "password": "Password1123"
}
